export const ADD_COUPON = 'ADD_COUPON';
export const DELETE_COUPON = 'DELETE_COUPON';
export const EDIT_COUPON = 'EDIT_COUPON';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_MODAL_EDIT = 'TOGGLE_MODAL_EDIT';
export const CLEAN_MODAL_STATE = 'CLEAN_MODAL_STATE';

