export const ADD_COUPON = 'ADD_COUPON';
export const DELETE_COUPON = 'DELETE_COUPON';
export const EDIT_COUPON = 'EDIT_COUPON';
export const TOGGLE_MODAL_ADDCOUPON = 'TOGGLE_MODAL_ADDCOUPON';
export const TOGGLE_MODAL_EDITCOUPON = 'TOGGLE_MODAL_EDITCOUPON';
export const GET_NEXT_COUPON_ID = 'GET_NEXT_COUPON_ID';

